services:
  - type: worker
    name: lxz-store-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        value: sqlite+aiosqlite:////app/data/lxz_store.db
      - key: STORE_NAME
        value: LXZ STORE BEST
      - key: CURRENCY
        value: USD
      - key: TIMEZONE
        value: America/Lima
      - key: SUPPORT_USERNAME
        value: Lxz_Modz
      - key: SUPPORT_URL
        value: https://t.me/Lxz_Modz
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5-mini
      - key: OPENAI_FALLBACK_MODEL
        value: gpt-5-nano
      - key: AI_COOLDOWN_SECONDS
        value: "2.0"
      - key: YAPE_NUMBER
        sync: false
      - key: PLIN_NUMBER
        sync: false
      - key: BINANCE_USDT_ENABLED
        value: "false"
      - key: BINANCE_USDT_ADDRESS
        sync: false
      - key: BINANCE_USDT_NETWORK
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PAGE_SIZE
        value: "6"
      - key: BROADCAST_DELAY
        value: "0.05"
      - key: PARTNER_FEE_USD
        value: "10.00"
      - key: PARTNER_DISCOUNT_PERCENT
        value: "20.00"
      - key: PREMIUN_FEE_USD
        value: "5.00"
      - key: PREMIUN_DISCOUNT_PERCENT
        value: "10.00"
    disk:
      name: lxz-store-data
      mountPath: /app/data
      sizeGB: 1
